import { createContext, useState, useContext } from 'react'

const translations = {
    en: {
        // Header & Nav
        search: 'Search', allCategory: 'All category', profile: 'Profile', message: 'Message',
        orders: 'Orders', myCart: 'My cart', hotOffers: 'Hot offers', giftBoxes: 'Gift boxes',
        projects: 'Projects', menuItem: 'Menu item', help: 'Help', shipTo: 'Ship to',
        // Hero
        latestTrending: 'Latest trending', electronicItems: 'Electronic items', learnMore: 'Learn more',
        joinNow: 'Join now', logIn: 'Log in', hiUser: 'Hi, user\nlet\'s get started',
        getDiscount: 'Get US $10 off with a new supplier',
        sendQuotes: 'Send quotes with supplier preferences',
        // Categories
        automobiles: 'Automobiles', clothesWear: 'Clothes and wear', homeInteriors: 'Home interiors',
        computerTech: 'Computer and tech', toolsEquipments: 'Tools, equipments',
        sportsOutdoor: 'Sports and outdoor', animalPets: 'Animal and pets',
        machineryTools: 'Machinery tools', moreCategory: 'More category',
        // Deals
        dealsOffers: 'Deals and offers', hygieneEquipments: 'Hygiene equipments',
        // Sections
        homeOutdoor: 'Home and outdoor', consumerElectronics: 'Consumer electronics and gadgets',
        inquirySend: 'An easy way to send inquiry', requestForQuote: 'Request for Quote',
        recommendedItems: 'Recommended items', ourExtraServices: 'Our extra services',
        suppliersByRegion: 'Suppliers by region', subscribeNewsletter: 'Subscribe on our newsletter',
        // Cart
        yourCartEmpty: 'Your cart is empty', startShopping: 'Start shopping',
        haveCoupon: 'Have a coupon?', addCoupon: 'Add coupon', apply: 'Apply',
        subtotal: 'Subtotal', tax: 'Tax', total: 'Total', discount: 'Discount',
        checkout: 'Checkout', continueShopping: 'Continue shopping', remove: 'Remove',
        // Checkout
        shippingInfo: 'Shipping Information', paymentMethod: 'Payment Method',
        reviewOrder: 'Review Your Order', firstName: 'First Name', lastName: 'Last Name',
        email: 'Email', phone: 'Phone', address: 'Address', city: 'City', state: 'State',
        zipCode: 'ZIP Code', country: 'Country', continuePayment: 'Continue to Payment',
        cardNumber: 'Card Number', expiryDate: 'Expiry Date', cvv: 'CVV',
        nameOnCard: 'Name on Card', placeOrder: 'Place Order', back: 'Back',
        orderPlaced: 'Order Placed Successfully!', orderConfirmMsg: 'Thank you for your purchase. You\'ll receive a confirmation email shortly.',
        shipping: 'Shipping', payment: 'Payment', confirm: 'Confirm',
        creditDebit: 'Credit / Debit Card', cashDelivery: 'Cash on Delivery',
        shippingTo: 'Shipping to', items: 'Items', orderSummary: 'Order Summary',
        freeShipping: 'Free shipping on orders over $100', free: 'Free',
        // PLP
        category: 'Category', brands: 'Brands', features: 'Features', seeAll: 'See all',
        itemsFound: 'items found', featured: 'Featured', gridView: 'Grid view', listView: 'List view',
        // PDP
        addToCart: 'Add to cart', buyNow: 'Buy now', description: 'Description',
        reviews: 'Reviews', relatedProducts: 'Related products',
        // Auth
        signIn: 'Sign in', signUp: 'Sign up', welcomeBack: 'Welcome back',
        createAccount: 'Create your account', password: 'Password', confirmPassword: 'Confirm Password',
        forgotPassword: 'Forgot password?', dontHaveAccount: 'Don\'t have an account?',
        alreadyHaveAccount: 'Already have an account?',
        // Footer
        aboutUs: 'About', partnership: 'Partnership', information: 'Information',
        forUsers: 'For users', getApp: 'Get app',
        // Validation
        required: 'is required', invalidEmail: 'Enter a valid email address',
        fillRequired: 'Please fill in all required fields to continue',
        fillPayment: 'Please fill in all payment details to continue',
        // Extra services
        sourceIndustry: 'Source from Industry Hubs', customizeProducts: 'Customize Your Products',
        fastShipping: 'Fast, reliable shipping by ocean or air', productMonitoring: 'Product monitoring and inspection',
    },
    es: {
        search: 'Buscar', allCategory: 'Todas las categorías', profile: 'Perfil', message: 'Mensaje',
        orders: 'Pedidos', myCart: 'Mi carrito', hotOffers: 'Ofertas', giftBoxes: 'Cajas de regalo',
        projects: 'Proyectos', menuItem: 'Menú', help: 'Ayuda', shipTo: 'Enviar a',
        latestTrending: 'Última tendencia', electronicItems: 'Artículos electrónicos', learnMore: 'Más información',
        joinNow: 'Únete ahora', logIn: 'Iniciar sesión', hiUser: 'Hola, usuario\ncomencemos',
        getDiscount: 'Obtén US $10 de descuento con un nuevo proveedor',
        sendQuotes: 'Envía cotizaciones con preferencias de proveedores',
        automobiles: 'Automóviles', clothesWear: 'Ropa y vestimenta', homeInteriors: 'Interiores del hogar',
        computerTech: 'Computadoras y tecnología', toolsEquipments: 'Herramientas y equipos',
        sportsOutdoor: 'Deportes y exterior', animalPets: 'Animales y mascotas',
        machineryTools: 'Herramientas de maquinaria', moreCategory: 'Más categorías',
        dealsOffers: 'Ofertas y descuentos', hygieneEquipments: 'Equipos de higiene',
        homeOutdoor: 'Hogar y exterior', consumerElectronics: 'Electrónica de consumo y gadgets',
        inquirySend: 'Una forma fácil de enviar consultas', requestForQuote: 'Solicitar cotización',
        recommendedItems: 'Artículos recomendados', ourExtraServices: 'Nuestros servicios extra',
        suppliersByRegion: 'Proveedores por región', subscribeNewsletter: 'Suscríbete a nuestro boletín',
        yourCartEmpty: 'Tu carrito está vacío', startShopping: 'Comenzar a comprar',
        haveCoupon: '¿Tienes un cupón?', addCoupon: 'Agregar cupón', apply: 'Aplicar',
        subtotal: 'Subtotal', tax: 'Impuesto', total: 'Total', discount: 'Descuento',
        checkout: 'Pagar', continueShopping: 'Seguir comprando', remove: 'Eliminar',
        shippingInfo: 'Información de envío', paymentMethod: 'Método de pago',
        reviewOrder: 'Revisar tu pedido', firstName: 'Nombre', lastName: 'Apellido',
        email: 'Correo', phone: 'Teléfono', address: 'Dirección', city: 'Ciudad', state: 'Estado',
        zipCode: 'Código postal', country: 'País', continuePayment: 'Continuar al pago',
        cardNumber: 'Número de tarjeta', expiryDate: 'Fecha de vencimiento', cvv: 'CVV',
        nameOnCard: 'Nombre en la tarjeta', placeOrder: 'Realizar pedido', back: 'Volver',
        orderPlaced: '¡Pedido realizado con éxito!', orderConfirmMsg: 'Gracias por tu compra. Recibirás un correo de confirmación pronto.',
        shipping: 'Envío', payment: 'Pago', confirm: 'Confirmar',
        creditDebit: 'Tarjeta de crédito / débito', cashDelivery: 'Pago contra entrega',
        shippingTo: 'Enviar a', items: 'Artículos', orderSummary: 'Resumen del pedido',
        freeShipping: 'Envío gratis en pedidos mayores a $100', free: 'Gratis',
        category: 'Categoría', brands: 'Marcas', features: 'Características', seeAll: 'Ver todo',
        itemsFound: 'artículos encontrados', featured: 'Destacado', gridView: 'Vista cuadrícula', listView: 'Vista lista',
        addToCart: 'Agregar al carrito', buyNow: 'Comprar ahora', description: 'Descripción',
        reviews: 'Reseñas', relatedProducts: 'Productos relacionados',
        signIn: 'Iniciar sesión', signUp: 'Registrarse', welcomeBack: 'Bienvenido de nuevo',
        createAccount: 'Crea tu cuenta', password: 'Contraseña', confirmPassword: 'Confirmar contraseña',
        forgotPassword: '¿Olvidaste tu contraseña?', dontHaveAccount: '¿No tienes cuenta?',
        alreadyHaveAccount: '¿Ya tienes cuenta?',
        aboutUs: 'Acerca de', partnership: 'Socios', information: 'Información',
        forUsers: 'Para usuarios', getApp: 'Obtener app',
        required: 'es obligatorio', invalidEmail: 'Ingresa un correo válido',
        fillRequired: 'Por favor completa todos los campos obligatorios', fillPayment: 'Por favor completa los datos de pago',
        sourceIndustry: 'Fuente de centros industriales', customizeProducts: 'Personaliza tus productos',
        fastShipping: 'Envío rápido y confiable por mar o aire', productMonitoring: 'Monitoreo e inspección de productos',
    },
    fr: {
        search: 'Rechercher', allCategory: 'Toutes catégories', profile: 'Profil', message: 'Message',
        orders: 'Commandes', myCart: 'Mon panier', hotOffers: 'Offres', giftBoxes: 'Coffrets cadeaux',
        projects: 'Projets', menuItem: 'Menu', help: 'Aide', shipTo: 'Livrer à',
        latestTrending: 'Dernières tendances', electronicItems: 'Articles électroniques', learnMore: 'En savoir plus',
        joinNow: 'Rejoindre', logIn: 'Se connecter', hiUser: 'Bonjour\ncommençons',
        getDiscount: 'Obtenez 10 $ de réduction avec un nouveau fournisseur',
        sendQuotes: 'Envoyez des devis avec les préférences fournisseurs',
        automobiles: 'Automobiles', clothesWear: 'Vêtements', homeInteriors: 'Intérieur maison',
        computerTech: 'Informatique', toolsEquipments: 'Outils et équipements',
        sportsOutdoor: 'Sports et plein air', animalPets: 'Animaux',
        machineryTools: 'Machines-outils', moreCategory: 'Plus de catégories',
        dealsOffers: 'Offres et promotions', hygieneEquipments: 'Équipements d\'hygiène',
        homeOutdoor: 'Maison et extérieur', consumerElectronics: 'Électronique grand public',
        inquirySend: 'Un moyen facile d\'envoyer une demande', requestForQuote: 'Demande de devis',
        recommendedItems: 'Articles recommandés', ourExtraServices: 'Nos services supplémentaires',
        suppliersByRegion: 'Fournisseurs par région', subscribeNewsletter: 'Abonnez-vous à notre newsletter',
        yourCartEmpty: 'Votre panier est vide', startShopping: 'Commencer vos achats',
        haveCoupon: 'Avez-vous un coupon?', addCoupon: 'Ajouter un coupon', apply: 'Appliquer',
        subtotal: 'Sous-total', tax: 'Taxe', total: 'Total', discount: 'Réduction',
        checkout: 'Paiement', continueShopping: 'Continuer vos achats', remove: 'Supprimer',
        shippingInfo: 'Informations de livraison', paymentMethod: 'Méthode de paiement',
        reviewOrder: 'Vérifier votre commande', firstName: 'Prénom', lastName: 'Nom',
        email: 'E-mail', phone: 'Téléphone', address: 'Adresse', city: 'Ville', state: 'État',
        zipCode: 'Code postal', country: 'Pays', continuePayment: 'Continuer vers le paiement',
        cardNumber: 'Numéro de carte', expiryDate: 'Date d\'expiration', cvv: 'CVV',
        nameOnCard: 'Nom sur la carte', placeOrder: 'Passer la commande', back: 'Retour',
        orderPlaced: 'Commande passée avec succès!', orderConfirmMsg: 'Merci pour votre achat. Vous recevrez un e-mail de confirmation.',
        shipping: 'Livraison', payment: 'Paiement', confirm: 'Confirmer',
        creditDebit: 'Carte de crédit / débit', cashDelivery: 'Paiement à la livraison',
        shippingTo: 'Livrer à', items: 'Articles', orderSummary: 'Récapitulatif',
        freeShipping: 'Livraison gratuite pour les commandes de plus de 100 $', free: 'Gratuit',
        category: 'Catégorie', brands: 'Marques', features: 'Caractéristiques', seeAll: 'Voir tout',
        itemsFound: 'articles trouvés', featured: 'En vedette', gridView: 'Vue grille', listView: 'Vue liste',
        addToCart: 'Ajouter au panier', buyNow: 'Acheter', description: 'Description',
        reviews: 'Avis', relatedProducts: 'Produits similaires',
        signIn: 'Se connecter', signUp: 'S\'inscrire', welcomeBack: 'Bienvenue',
        createAccount: 'Créez votre compte', password: 'Mot de passe', confirmPassword: 'Confirmer le mot de passe',
        forgotPassword: 'Mot de passe oublié?', dontHaveAccount: 'Pas encore de compte?',
        alreadyHaveAccount: 'Déjà un compte?',
        aboutUs: 'À propos', partnership: 'Partenariat', information: 'Information',
        forUsers: 'Pour les utilisateurs', getApp: 'Application',
        required: 'est obligatoire', invalidEmail: 'Entrez un e-mail valide',
        fillRequired: 'Veuillez remplir tous les champs obligatoires', fillPayment: 'Veuillez remplir les détails de paiement',
        sourceIndustry: 'Source des centres industriels', customizeProducts: 'Personnalisez vos produits',
        fastShipping: 'Expédition rapide par mer ou air', productMonitoring: 'Surveillance et inspection des produits',
    },
    de: {
        search: 'Suchen', allCategory: 'Alle Kategorien', profile: 'Profil', message: 'Nachricht',
        orders: 'Bestellungen', myCart: 'Warenkorb', hotOffers: 'Angebote', giftBoxes: 'Geschenkboxen',
        projects: 'Projekte', menuItem: 'Menü', help: 'Hilfe', shipTo: 'Versand nach',
        latestTrending: 'Neueste Trends', electronicItems: 'Elektronik', learnMore: 'Mehr erfahren',
        joinNow: 'Jetzt beitreten', logIn: 'Anmelden', hiUser: 'Hallo\nlos geht\'s',
        getDiscount: '10 $ Rabatt mit einem neuen Lieferanten',
        sendQuotes: 'Angebote mit Lieferantenpräferenzen senden',
        automobiles: 'Automobile', clothesWear: 'Kleidung', homeInteriors: 'Wohnräume',
        computerTech: 'Computer & Technik', toolsEquipments: 'Werkzeuge',
        sportsOutdoor: 'Sport & Outdoor', animalPets: 'Tiere & Haustiere',
        machineryTools: 'Maschinenwerkzeuge', moreCategory: 'Mehr Kategorien',
        dealsOffers: 'Angebote & Rabatte', hygieneEquipments: 'Hygieneausrüstung',
        homeOutdoor: 'Haus & Garten', consumerElectronics: 'Unterhaltungselektronik',
        inquirySend: 'Einfach Anfragen senden', requestForQuote: 'Angebot anfordern',
        recommendedItems: 'Empfohlene Artikel', ourExtraServices: 'Unsere Zusatzleistungen',
        suppliersByRegion: 'Lieferanten nach Region', subscribeNewsletter: 'Newsletter abonnieren',
        yourCartEmpty: 'Ihr Warenkorb ist leer', startShopping: 'Einkaufen starten',
        haveCoupon: 'Haben Sie einen Gutschein?', addCoupon: 'Gutschein eingeben', apply: 'Anwenden',
        subtotal: 'Zwischensumme', tax: 'Steuer', total: 'Gesamt', discount: 'Rabatt',
        checkout: 'Zur Kasse', continueShopping: 'Weiter einkaufen', remove: 'Entfernen',
        shippingInfo: 'Versandinformationen', paymentMethod: 'Zahlungsmethode',
        reviewOrder: 'Bestellung prüfen', firstName: 'Vorname', lastName: 'Nachname',
        email: 'E-Mail', phone: 'Telefon', address: 'Adresse', city: 'Stadt', state: 'Bundesland',
        zipCode: 'PLZ', country: 'Land', continuePayment: 'Weiter zur Zahlung',
        cardNumber: 'Kartennummer', expiryDate: 'Ablaufdatum', cvv: 'CVV',
        nameOnCard: 'Name auf der Karte', placeOrder: 'Bestellung aufgeben', back: 'Zurück',
        orderPlaced: 'Bestellung erfolgreich aufgegeben!', orderConfirmMsg: 'Vielen Dank für Ihren Einkauf. Sie erhalten eine Bestätigungs-E-Mail.',
        shipping: 'Versand', payment: 'Zahlung', confirm: 'Bestätigen',
        creditDebit: 'Kredit-/Debitkarte', cashDelivery: 'Nachnahme',
        shippingTo: 'Versand an', items: 'Artikel', orderSummary: 'Bestellübersicht',
        freeShipping: 'Kostenloser Versand ab $100', free: 'Kostenlos',
        category: 'Kategorie', brands: 'Marken', features: 'Merkmale', seeAll: 'Alle anzeigen',
        itemsFound: 'Artikel gefunden', featured: 'Empfohlen', gridView: 'Rasteransicht', listView: 'Listenansicht',
        addToCart: 'In den Warenkorb', buyNow: 'Jetzt kaufen', description: 'Beschreibung',
        reviews: 'Bewertungen', relatedProducts: 'Ähnliche Produkte',
        signIn: 'Anmelden', signUp: 'Registrieren', welcomeBack: 'Willkommen zurück',
        createAccount: 'Konto erstellen', password: 'Passwort', confirmPassword: 'Passwort bestätigen',
        forgotPassword: 'Passwort vergessen?', dontHaveAccount: 'Kein Konto?',
        alreadyHaveAccount: 'Bereits ein Konto?',
        aboutUs: 'Über uns', partnership: 'Partnerschaft', information: 'Information',
        forUsers: 'Für Nutzer', getApp: 'App herunterladen',
        required: 'ist erforderlich', invalidEmail: 'Gültige E-Mail eingeben',
        fillRequired: 'Bitte füllen Sie alle Pflichtfelder aus', fillPayment: 'Bitte füllen Sie die Zahlungsdaten aus',
        sourceIndustry: 'Industriezentren', customizeProducts: 'Produkte anpassen',
        fastShipping: 'Schneller Versand per See oder Luft', productMonitoring: 'Produktüberwachung und Inspektion',
    },
    ar: {
        search: 'بحث', allCategory: 'جميع الفئات', profile: 'الملف الشخصي', message: 'رسالة',
        orders: 'الطلبات', myCart: 'سلة التسوق', hotOffers: 'عروض ساخنة', giftBoxes: 'صناديق الهدايا',
        projects: 'المشاريع', menuItem: 'القائمة', help: 'مساعدة', shipTo: 'الشحن إلى',
        latestTrending: 'أحدث الاتجاهات', electronicItems: 'الأجهزة الإلكترونية', learnMore: 'اعرف المزيد',
        joinNow: 'انضم الآن', logIn: 'تسجيل الدخول', hiUser: 'مرحباً\nلنبدأ',
        getDiscount: 'احصل على خصم 10$ مع مورد جديد',
        sendQuotes: 'أرسل عروض أسعار مع تفضيلات الموردين',
        automobiles: 'سيارات', clothesWear: 'ملابس', homeInteriors: 'ديكور المنزل',
        computerTech: 'حاسوب وتقنية', toolsEquipments: 'أدوات ومعدات',
        sportsOutdoor: 'رياضة وهواء طلق', animalPets: 'حيوانات أليفة',
        machineryTools: 'أدوات آلية', moreCategory: 'المزيد من الفئات',
        dealsOffers: 'عروض وتخفيضات', hygieneEquipments: 'معدات النظافة',
        homeOutdoor: 'المنزل والخارج', consumerElectronics: 'إلكترونيات استهلاكية',
        inquirySend: 'طريقة سهلة لإرسال الاستفسارات', requestForQuote: 'طلب عرض سعر',
        recommendedItems: 'منتجات مقترحة', ourExtraServices: 'خدماتنا الإضافية',
        suppliersByRegion: 'الموردون حسب المنطقة', subscribeNewsletter: 'اشترك في النشرة الإخبارية',
        yourCartEmpty: 'سلة التسوق فارغة', startShopping: 'ابدأ التسوق',
        haveCoupon: 'لديك كوبون؟', addCoupon: 'أدخل الكوبون', apply: 'تطبيق',
        subtotal: 'المجموع الفرعي', tax: 'الضريبة', total: 'الإجمالي', discount: 'الخصم',
        checkout: 'الدفع', continueShopping: 'متابعة التسوق', remove: 'إزالة',
        shippingInfo: 'معلومات الشحن', paymentMethod: 'طريقة الدفع',
        reviewOrder: 'مراجعة الطلب', firstName: 'الاسم الأول', lastName: 'اسم العائلة',
        email: 'البريد الإلكتروني', phone: 'الهاتف', address: 'العنوان', city: 'المدينة', state: 'الولاية',
        zipCode: 'الرمز البريدي', country: 'الدولة', continuePayment: 'متابعة الدفع',
        cardNumber: 'رقم البطاقة', expiryDate: 'تاريخ الانتهاء', cvv: 'CVV',
        nameOnCard: 'الاسم على البطاقة', placeOrder: 'تأكيد الطلب', back: 'رجوع',
        orderPlaced: 'تم تقديم الطلب بنجاح!', orderConfirmMsg: 'شكراً لشرائك. ستتلقى بريداً إلكترونياً للتأكيد.',
        shipping: 'الشحن', payment: 'الدفع', confirm: 'تأكيد',
        creditDebit: 'بطاقة ائتمان / خصم', cashDelivery: 'الدفع عند الاستلام',
        shippingTo: 'الشحن إلى', items: 'منتجات', orderSummary: 'ملخص الطلب',
        freeShipping: 'شحن مجاني للطلبات فوق 100$', free: 'مجاني',
        category: 'الفئة', brands: 'العلامات التجارية', features: 'الميزات', seeAll: 'عرض الكل',
        itemsFound: 'منتج موجود', featured: 'مميز', gridView: 'عرض شبكي', listView: 'عرض قائمة',
        addToCart: 'أضف للسلة', buyNow: 'اشتري الآن', description: 'الوصف',
        reviews: 'التقييمات', relatedProducts: 'منتجات مشابهة',
        signIn: 'تسجيل الدخول', signUp: 'إنشاء حساب', welcomeBack: 'مرحباً بعودتك',
        createAccount: 'أنشئ حسابك', password: 'كلمة المرور', confirmPassword: 'تأكيد كلمة المرور',
        forgotPassword: 'نسيت كلمة المرور؟', dontHaveAccount: 'ليس لديك حساب؟',
        alreadyHaveAccount: 'لديك حساب بالفعل؟',
        aboutUs: 'عن الموقع', partnership: 'شراكة', information: 'معلومات',
        forUsers: 'للمستخدمين', getApp: 'حمل التطبيق',
        required: 'مطلوب', invalidEmail: 'أدخل بريد إلكتروني صالح',
        fillRequired: 'يرجى ملء جميع الحقول المطلوبة', fillPayment: 'يرجى ملء بيانات الدفع',
        sourceIndustry: 'مراكز صناعية', customizeProducts: 'خصص منتجاتك',
        fastShipping: 'شحن سريع عبر البحر أو الجو', productMonitoring: 'مراقبة وفحص المنتجات',
    },
    zh: {
        search: '搜索', allCategory: '所有分类', profile: '个人中心', message: '消息',
        orders: '订单', myCart: '购物车', hotOffers: '热门优惠', giftBoxes: '礼品盒',
        projects: '项目', menuItem: '菜单', help: '帮助', shipTo: '送达',
        latestTrending: '最新趋势', electronicItems: '电子产品', learnMore: '了解更多',
        joinNow: '立即加入', logIn: '登录', hiUser: '你好\n开始吧',
        getDiscount: '新供应商立减10美元',
        sendQuotes: '按供应商偏好发送报价',
        automobiles: '汽车', clothesWear: '服装', homeInteriors: '家居装饰',
        computerTech: '电脑与技术', toolsEquipments: '工具设备',
        sportsOutdoor: '运动与户外', animalPets: '宠物',
        machineryTools: '机械工具', moreCategory: '更多分类',
        dealsOffers: '优惠活动', hygieneEquipments: '卫生设备',
        homeOutdoor: '家居与户外', consumerElectronics: '消费电子',
        inquirySend: '轻松发送询价', requestForQuote: '请求报价',
        recommendedItems: '推荐商品', ourExtraServices: '额外服务',
        suppliersByRegion: '按地区查找供应商', subscribeNewsletter: '订阅我们的通讯',
        yourCartEmpty: '购物车为空', startShopping: '开始购物',
        haveCoupon: '有优惠券？', addCoupon: '输入优惠券', apply: '使用',
        subtotal: '小计', tax: '税费', total: '合计', discount: '折扣',
        checkout: '结算', continueShopping: '继续购物', remove: '移除',
        shippingInfo: '收货信息', paymentMethod: '支付方式',
        reviewOrder: '确认订单', firstName: '名', lastName: '姓',
        email: '邮箱', phone: '电话', address: '地址', city: '城市', state: '省份',
        zipCode: '邮编', country: '国家', continuePayment: '继续支付',
        cardNumber: '卡号', expiryDate: '有效期', cvv: 'CVV',
        nameOnCard: '持卡人姓名', placeOrder: '提交订单', back: '返回',
        orderPlaced: '订单提交成功！', orderConfirmMsg: '感谢您的购买，确认邮件即将发送。',
        shipping: '配送', payment: '支付', confirm: '确认',
        creditDebit: '信用卡/借记卡', cashDelivery: '货到付款',
        shippingTo: '配送至', items: '件商品', orderSummary: '订单摘要',
        freeShipping: '满100美元免运费', free: '免费',
        category: '分类', brands: '品牌', features: '特性', seeAll: '查看全部',
        itemsFound: '件商品', featured: '精选', gridView: '网格视图', listView: '列表视图',
        addToCart: '加入购物车', buyNow: '立即购买', description: '描述',
        reviews: '评价', relatedProducts: '相关商品',
        signIn: '登录', signUp: '注册', welcomeBack: '欢迎回来',
        createAccount: '创建账户', password: '密码', confirmPassword: '确认密码',
        forgotPassword: '忘记密码？', dontHaveAccount: '没有账户？',
        alreadyHaveAccount: '已有账户？',
        aboutUs: '关于', partnership: '合作', information: '信息',
        forUsers: '用户服务', getApp: '下载APP',
        required: '必填', invalidEmail: '请输入有效邮箱',
        fillRequired: '请填写所有必填项', fillPayment: '请填写支付信息',
        sourceIndustry: '工业中心采购', customizeProducts: '定制您的产品',
        fastShipping: '海运或空运快速配送', productMonitoring: '产品监控与检验',
    },
}

const languages = [
    { code: 'en', label: 'English', flag: '🇺🇸' },
    { code: 'es', label: 'Español', flag: '🇪🇸' },
    { code: 'fr', label: 'Français', flag: '🇫🇷' },
    { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
    { code: 'ar', label: 'العربية', flag: '🇸🇦' },
    { code: 'zh', label: '中文', flag: '🇨🇳' },
]

const LanguageContext = createContext()

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState('en')
    const t = (key) => translations[lang]?.[key] || translations.en[key] || key
    const currentLang = languages.find(l => l.code === lang)
    return (
        <LanguageContext.Provider value={{ lang, setLang, t, languages, currentLang }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLanguage = () => useContext(LanguageContext)
export default LanguageContext
